name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "nalgebra", "ndarray", "serde", "python", "python_macro"]

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --no-default-features --features "${{ matrix.features }}"
      - name: Run tests
        run: cargo test --release --no-default-features --features "${{ matrix.features }}"
